//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coverable
    {
        public int CoverableNumber { get; set; }
        public string Details { get; set; }
        public Nullable<int> PolicyNumber { get; set; }
    
        public virtual Policy Policy { get; set; }
    }
}
